const types = {
  START_PAGE_LOAD: '@@loader/START_PAGE_LOAD',
  STOP_PAGE_LOAD: '@@loader/STOP_PAGE_LOAD',
  BEGIN_AJAX_CALL: '@@loader/BEGIN_AJAX_CALL',
  AJAX_CALL_ERROR: '@@loader/AJAX_CALL_ERROR',
  USER_LOGGED_IN: '@@user/USER_LOGGED_IN',
  USER_LOGGED_OUT: '@@user/USER_LOGGED_OUT',
  USER_LOGIN_FAILED: '@@user/USER_LOGIN_FAILED',
  USER_LOGOUT_FAILED: '@@user/USER_LOGOUT_FAILED',
  USER_DATA_LOAD_SUCCESS: '@@user/USER_DATA_LOAD_SUCCESS',
  USER_DATA_LOAD_FAILED: '@@user/USER_DATA_LOAD_FAILED',
  SET_REDIRECT_URL: '@@route/SET_REDIRECT_URL',
  REDIRECT_APP: '@@route/REDIRECT_APPLICATION'
};

export default types;
